### ISSUE TITLE
Getting more detail, I like it!

### ISSUE THREAD

**Issue by driskerr** [kaumaron/musclehub_submission#2]
https://github.com/kaumaron/musclehub_submission/blob/dafbc9654016b1b3e20288bfcec15227c7fe0d2a/musclehub.py#L113-L114

You're pulling in additional columns that we did not specify, wondering what you're going to use them for! Excited to see your analysis!

**Comment by kaumaron** [comment]
When I was adding in the gender I thought it would be interesting to look as that as an additional dimension but I ended up losing track of it while working through the rest of the project which is disappointing.
