### ISSUE TITLE
Nice summary statements

### ISSUE THREAD

**Issue by driskerr** [kaumaron/musclehub_submission#4]
https://github.com/kaumaron/musclehub_submission/blob/dafbc9654016b1b3e20288bfcec15227c7fe0d2a/musclehub.py#L154-L155

Did we ever cover string replacers with `.format()`? Anyway good work! This is the current, up-to-date method for printing passing data into strings and print to the terminal. You are clearly bringing in outside knowledge or did some good research!

**Comment by kaumaron** [comment]
No we didn't discuss `.format()` in the course, but I use it all the time in other projects.
