### ISSUE TITLE
Much appreciated!

### ISSUE THREAD

**Issue by driskerr** [kaumaron/musclehub_submission#5]
https://github.com/kaumaron/musclehub_submission/blob/dafbc9654016b1b3e20288bfcec15227c7fe0d2a/musclehub.py#L168

Good use of the "magic line" to generate graphs within the notebook. Another way of executing this is: `%matplotlib inline`

**Comment by kaumaron** [comment]
I actually did use `%matplotlib inline` and I think this appeared when I exported as `.py`
