### ISSUE TITLE
Executes correctly, but want to point out a technicality

### ISSUE THREAD

**Issue by driskerr** [kaumaron/musclehub_submission#6]
https://github.com/kaumaron/musclehub_submission/blob/dafbc9654016b1b3e20288bfcec15227c7fe0d2a/musclehub.py#L177

It's good practice when working with `None` data types to use the operators 
`is` or `pd.isnull()` __instead_ of_ `==`  
and 
`is not` or `pd.notnull()` __instead_ of_ `!=`.

The reason for this is that by definition , `None` is not a value and something cannot be equal to it. However, the people you write python know that people often make the same assumpution as you and made a workaround where `==None` will raise `is None`. You can read up on it [here](http://jaredgrubb.blogspot.com/2009/04/python-is-none-vs-none.html). Your code executes correctly as written, so no worries here.

**Comment by kaumaron** [comment]
Thanks for pointing that out! I'll keep it in mind from now on.
